### ISSUE TITLE
Add a getting started guide in the lower portion of readme

### ISSUE THREAD

**Issue by opticSquid** [opticSquid/hive#12]
Need to add a getting started guide to the lower portion of readme where first time contributors know how to get started in contributing like from installing `git`, an IDE like `vs code` and git commands to clone the repo and all kind of just summarize the [contributing.md](https://github.com/opticSquid/hive/blob/main/CONTRIBUTING.md) starting from a beginner's perspective till guiding them to making their PR

**Comment by raxvab** [comment]
I want to work on this issue under JWOC

**Comment by opticSquid** [comment]
I have assigned the issue to you

**Comment by opticSquid** [comment]
As per the event guidelines the easy issue was meant to have a PR by 24 hours but 2 days have gone by so I'm unassigning this issue from you and making it available for grab

**Comment by raxvab** [comment]
hello @opticSquid Could you please elaborate what content you want updated in readme.md file as I can see there the contribution details are the one which are missing but attached in contribution file.

**Comment by raxvab** [comment]
> As per the event guidelines the easy issue was meant to have a PR by 24 hours but 2 days have gone by so I'm unassigning this issue from you and making it available for grab

If I make a pull request now would that be valid?

**Comment by raxvab** [comment]
> As per the event guidelines the easy issue was meant to have a PR by 24 hours but 2 days have gone by so I'm unassigning this issue from you and making it available for grab

Could you please reassign the issue as It was a lack of acknowledgement that I'd been assigned this one too.

**Comment by opticSquid** [comment]
Well I want a brief summary of `contributing.md` file be attatched in the readme file. like the commands to install the dependencies and commands to start the servers. Its like the minimum set of commands to get started to work.

**Comment by opticSquid** [comment]
Okay I'm reassigning you to this issue

**Comment by raxvab** [comment]
Thank you

**Comment by opticSquid** [comment]
but a pr should be made within 24hrs to acknowledge the event rules

**Comment by raxvab** [comment]
> but a pr should be made within 24hrs to acknowledge the event rules

Is there any way this could be put under some other category? and even if it's not No problem from my side as I learned a bit about editing Readme.md file
