### ISSUE TITLE
Create Issue Templates for the repo

### ISSUE THREAD

**Issue by opticSquid** [opticSquid/hive#31]
Create `Bug-report` and `Feature-request` templates for the repo.
The previous templates were faulty and github was not detecting them..

To create issue templates read this article(s):
+ [using templates to encourage useful issues and pull requests ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by thatsuman** [comment]
I would like to work on this issue under JWOC

**Comment by opticSquid** [comment]
ok I'm assigning you this issue.
