### ISSUE TITLE
[Bug]: Change the component name of the component under website/src/Pages  from App to any other name 

### ISSUE THREAD

**Issue by opticSquid** [opticSquid/hive#43]
### Expected Behavior

In website folder which contains the react app, there should be no imported child component of same name as of the name of parent function.

### Current Behavior

In website folder which contains the react app, there is a component under `website/src/pages` which has a name **App.jsx** when imported to App.js under `/src` folder to render it , being of the same name the import conflicts.. Change the name of the file under 
`website/src/pages` from `App.jsx` to any other suitable name and change the name of the class too that it exports. After that change the import in the `website/src/App.js` to reflect the change.

### Steps to Reproduce

1. Run the following commands from your terminal after installing the dependencies of `website` folder:

```sh
npm start
```
2. See the error log.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tess-Vanta** [comment]
I want to take this up under JWOC

**Comment by opticSquid** [comment]
Okay assigning you..
