### ISSUE TITLE
Render error page and return back to previous page whenever error is encountered.

### ISSUE THREAD

**Issue by opticSquid** [opticSquid/hive#5]
Find a way to render a default error page with a dynamic error message and whenever back is clicked, it should return to the last visited page rather than the home page

**Comment by KiDxS** [comment]
May I know if we already have a error page?

Or do I have to create it for myself?

**Comment by opticSquid** [comment]
You have to create one if you can we are cleaning up the existing react app to start all over you can initialize a `create-react-app` in the website folder and create a error page and the routes to render it. There is another issue in the repo to clean the react app if you want I can assign you that issue too..

**Comment by opticSquid** [comment]
If you want to work on it please comment below

**Comment by KiDxS** [comment]
Can I work on this?

**Comment by opticSquid** [comment]
Yeah you can I have deleted the existing react app because it had lot of bugs we are starting over it currently contains the default `create-react-app` template you can create an error page and put that there with the routes..

**Comment by opticSquid** [comment]
I'm assigning this issue to you

**Comment by opticSquid** [comment]
are you working under JWOC or just normally

**Comment by KiDxS** [comment]
Im currently working under jwoc
